services:
  db:
    container_name: sql_server_local
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init.sql:/init.sql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "SuperPassword123!", "-C", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_init
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - ./init.sql:/init.sql
    command: >
      /bin/bash -c "
      /opt/mssql-tools18/bin/sqlcmd -S db -U sa -P SuperPassword123! -C -i /init.sql &&
      echo 'Base de datos inicializada correctamente'
      "
    restart: "no"

  api:
    container_name: python_api_local
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      db-init:
        condition: service_completed_successfully
    environment:
      - DB_SERVER=db
      - DB_NAME=db_cotizaciones
    volumes:
      - ./api:/app
  
volumes:
  sqlserver_data:
